Vagrant.configure("2") do |config|

    config.vm.box = "bento/oracle-7.6"
    config.vm.hostname = "test1"
    config.vm.network "public_network", bridge: "eno1"
    config.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "test1"
      vb.cpus = "1"
    end

end
