Vagrant.configure("2") do |config|

    config.vm.box = ":box:"
    config.vm.hostname = ":hostname:"
    config.vm.network "public_network", bridge: "eno1"
    config.vm.network "private_network", type: "dhcp"

    config.vm.synced_folder "/111/containers/shared/data", "/vagrant_data", id: "shared"
    config.vm.synced_folder "/111/staging", "/staging", id: "stage"
    config.vm.synced_folder "/111/Software", "/software", id: "sofware"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = ":mem:"
      vb.name = ":hostname:"
      vb.cpus = ":cpus:"
    end

end
